// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dance.API.Data;

#nullable disable

namespace dance.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513224728_FixAllRelationships")]
    partial class FixAllRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dance.API.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Record_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Record_id"));

                    b.Property<int>("Class_id")
                        .HasColumnType("int");

                    b.Property<int>("Client_id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Record_id");

                    b.HasIndex("Class_id");

                    b.HasIndex("Client_id");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("dance.API.Models.Class", b =>
                {
                    b.Property<int>("Class_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Class_id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Group_id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<int>("Trainer_id")
                        .HasColumnType("int");

                    b.HasKey("Class_id");

                    b.HasIndex("Group_id");

                    b.HasIndex("Trainer_id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("dance.API.Models.Client", b =>
                {
                    b.Property<int>("Client_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Client_id");

                    b.HasIndex("User_id")
                        .IsUnique()
                        .HasFilter("[User_id] IS NOT NULL");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("dance.API.Models.Direction", b =>
                {
                    b.Property<int>("Direction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Direction_id"));

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Direction_id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("dance.API.Models.Group", b =>
                {
                    b.Property<int>("Group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Group_id"));

                    b.Property<int>("Direction_id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trainer_id")
                        .HasColumnType("int");

                    b.HasKey("Group_id");

                    b.HasIndex("Direction_id");

                    b.HasIndex("Trainer_id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("dance.API.Models.Registration", b =>
                {
                    b.Property<int>("Registration_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Registration_id"));

                    b.Property<int>("Client_id")
                        .HasColumnType("int");

                    b.Property<int>("Group_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Registration_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Registration_id");

                    b.HasIndex("Client_id");

                    b.HasIndex("Group_id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("dance.API.Models.Subscription", b =>
                {
                    b.Property<int>("Sub_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sub_id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Client_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Group_id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sub_id");

                    b.HasIndex("Client_id");

                    b.HasIndex("Group_id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("dance.API.Models.Trainer", b =>
                {
                    b.Property<int>("Trainer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trainer_id"));

                    b.Property<int>("Direction_id")
                        .HasColumnType("int");

                    b.Property<int?>("Direction_id1")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Trainer_id");

                    b.HasIndex("Direction_id1");

                    b.HasIndex("User_id")
                        .IsUnique()
                        .HasFilter("[User_id] IS NOT NULL");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("dance.API.Models.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_id"));

                    b.Property<int?>("Client_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Trainer_id")
                        .HasColumnType("int");

                    b.HasKey("User_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dance.API.Models.AttendanceRecord", b =>
                {
                    b.HasOne("dance.API.Models.Class", "Class")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("Class_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dance.API.Models.Client", "Client")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("Client_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("dance.API.Models.Class", b =>
                {
                    b.HasOne("dance.API.Models.Group", "Group")
                        .WithMany("Classes")
                        .HasForeignKey("Group_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dance.API.Models.Trainer", "Trainer")
                        .WithMany("Classes")
                        .HasForeignKey("Trainer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("dance.API.Models.Client", b =>
                {
                    b.HasOne("dance.API.Models.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("dance.API.Models.Client", "User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("dance.API.Models.Group", b =>
                {
                    b.HasOne("dance.API.Models.Direction", "Direction")
                        .WithMany("Groups")
                        .HasForeignKey("Direction_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dance.API.Models.Trainer", "Trainer")
                        .WithMany("Groups")
                        .HasForeignKey("Trainer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direction");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("dance.API.Models.Registration", b =>
                {
                    b.HasOne("dance.API.Models.Client", "Client")
                        .WithMany("Registrations")
                        .HasForeignKey("Client_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dance.API.Models.Group", "Group")
                        .WithMany("Registrations")
                        .HasForeignKey("Group_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("dance.API.Models.Subscription", b =>
                {
                    b.HasOne("dance.API.Models.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Client_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dance.API.Models.Group", "Group")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Group_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("dance.API.Models.Trainer", b =>
                {
                    b.HasOne("dance.API.Models.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("Direction_id1");

                    b.HasOne("dance.API.Models.User", "User")
                        .WithOne("Trainer")
                        .HasForeignKey("dance.API.Models.Trainer", "User_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Direction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dance.API.Models.Class", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("dance.API.Models.Client", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Registrations");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("dance.API.Models.Direction", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("dance.API.Models.Group", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Registrations");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("dance.API.Models.Trainer", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("dance.API.Models.User", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Trainer");
                });
#pragma warning restore 612, 618
        }
    }
}
